### ISSUE TITLE
Merging before build is completed errors out

### ISSUE THREAD

**Issue by tmigone** [balena-io/deploy-to-balena-action#82]
When merging a PR if the draft release has not finished building then the action will error out with:

```
Error: Did not find any matching releases
```

I think this is because of the filters applied here when querying for the release: https://github.com/balena-io/deploy-to-balena-action/blob/6cacfa61a02a534bdb702a56e1d43e375449a926/src/balena-utils.ts#L165-L173

The query expects a release with `status: 'success'` and doesn't consider the possibility of the release being still being in `status: 'running'`. This results in the action not finalizing the release even if it eventually succeeds. 

We can't however change the `status: success` filter to `status: running` because that would risk tagging a build that eventually failed... so not sure what we can do 😵‍💫 

For an example see:
- balenaSound PR --> https://github.com/balenalabs/balena-sound/pull/534
- Action run due to PR created/updated --> https://github.com/balenalabs/balena-sound/actions/runs/1677745413
- Action run due to PR merged --> https://github.com/balenalabs/balena-sound/actions/runs/1677756132

**Comment by tmigone** [comment]
BTW this bug made me run `balena push` like I'm a peasant living in 2020 😭

**Comment by 20k-ultra** [comment]
You have to configure your repository to require the action to pass before merging because otherwise the PR workflow is a facade.

One of the best things about this action is it allows you to create a build at PR to tests and review then on merge what you tested is exactly what gets deployed / merged to master. We can't modify this characteristic by looking for running builds since that violates this.
